# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test-job:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run tests!
      - run:
          name: Run Tests
          command: npm test
      # Save Coverage info for later publish
      - save_cache:
          paths:
            - tests/coverage/lcov.info
          key: coverage-info

  publish-job:
    docker:
      - image: circleci/node:9
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Build
          command: npm run build:prod
      - run:
          name: Publish Package
          command: cd dist && npm run semantic-release
      - restore_cache:
          keys:
            - coverage-info
      - run:
          name: Publish Coverage
          command: npm run coveralls

workflows:
  version: 2
  test:
    jobs:
      - test-job
      - publish-job:
          requires:
            - test-job
          filters:
            branches:
              only:
                - master
